himalayanyeti/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls')),
]

if settings.DEBUG:  
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)  

mainapp/urls.py
from mainapp import views
from django.urls import path

urlpatterns = [
    path('', views.home, name='home'),
    path('index', views.home, name='index'),
    path('donation', views.donation, name='donation'),
    path('help', views.help, name='help'),
    path('userlogin', views.userlogin, name='userlogin'),
    path('userlogout', views.userlogout, name='userlogout'),
    path('createuser', views.createuser, name='createuser'),
    path('addarticle', views.addarticle, name='addarticle'),

    path('about', views.about, name='about'),
    path('contact', views.contact, name='contact'),
    path('government', views.government, name='government'),
    path('organisation', views.organisation, name='organisation'),
    path('institute', views.institute, name='institute'),
    path('individual', views.individual, name='individual'),
    path('csr', views.csr, name='csr'),
    path('getinvolved', views.getinvolved, name='getinvolved'),
    path('focusArea', views.focusArea, name='focusArea'),
    path('testimonial', views.testimonial, name='testimonial'),






    path('deletearticle/<int:num>', views.deletearticle, name="deletearticle"),
    path('viewarticle/<int:num>', views.viewarticle, name="viewarticle"),
    path('updatearticle/<int:pk>', views.updatearticle, name="updatearticle"),







]

mainapp/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField


# Create your models here.

class categories(models.Model):
    cid = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class label(models.Model):
    lid = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255)
    parentcategory = models.ForeignKey(categories, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.name}({self.parentcategory})"


class article(models.Model):
    bid = models.AutoField(primary_key=True)
    title = models.CharField(max_length=255, null=True)
    # headerimage = models.ImageField()
    headerimage = models.ImageField(null=True, upload_to="images")
    # author = models.CharField(max_length=255)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    postdate = models.DateTimeField(editable=False, auto_now=True) 
    # category = models.CharField(max_length=255)
    category = models.ForeignKey(categories, on_delete=models.CASCADE)
    # label = models.CharField(max_length=255)
    label = models.ForeignKey(label, on_delete=models.CASCADE)
    # body = models.TextField(blank=True, null=True)
    body = RichTextField(blank=True, null=True)
    snippet = models.CharField(max_length=255)

    def __str__(self):
        return f"Title: {self.title} (Author: {self.author})"

class subscriber(models.Model):
    eid = models.AutoField(primary_key=True)
    mail = models.EmailField(max_length = 254)
    isactive = models.BooleanField(default=True)

    def __str__(self):
        status=""
        if self.isactive==True:
            status="ACTIVE"
        else:
            status="DEACTIVE"
        return f"{self.mail}|({status})"

mainapp/forms.py
from django import forms
from . models import article, label, categories

from django.forms import inlineformset_factory

class articleform(forms.ModelForm):
    class Meta:
        model=article
        fields="__all__"

mainapp/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth  import authenticate, login, logout
from django.contrib.auth.models import User
from . forms import articleform
from mainapp.models import article, label, categories, subscriber

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from django.contrib.auth.decorators import login_required

# Imports to send email
from django.conf import settings
from django.http import HttpResponse
from django.core.mail import EmailMultiAlternatives, send_mail
from django.template.loader import render_to_string
from django.utils.html import strip_tags

# Global variables

labelvalue=0                            #used in help function to keep track of filter in help section

# Create your views here.

def sendWelcomeMail(mail):
    send_to=[]
    send_to.append(mail)
    contex={}
    contex['mailid']=mail.split('@')[0]
    html_content = render_to_string("mainapp/emailtemplate/welcome.html", contex)
    text_content = strip_tags(html_content)
    email = EmailMultiAlternatives(
        "Thanks for Subscribing Himalayan Yeti Foundation",
        text_content,
        settings.EMAIL_HOST_USER ,
        send_to
    )
    email.attach_alternative(html_content, 'text/html')
    print(email)
    email.send()
    return 

def home(request):
    contex={}
    if request.method == 'POST' and 'scrubmail' in request.POST:
        scrubmail = request.POST['scrubmail']
        mail = subscriber.objects.create(mail=scrubmail)
        sendWelcomeMail(scrubmail)
        mail.save()
    eventlist = article.objects.filter(category=6).order_by('-postdate')[0:3]
    contex['eventlist']=eventlist
    return render(request, "mainapp/index.html", contex)

def donation(request):
    return render(request, "mainapp/donation.html")

def help(request):
    contex={}
    global labelvalue
    labelvalue = int(request.GET.get('label', labelvalue))
    if labelvalue==0:
        object_list = article.objects.filter(category=5).order_by('-postdate') # category 5 belongs to help/blog
    else:
        object_list = article.objects.filter(label=labelvalue).order_by('-postdate')

    page_num = request.GET.get('page', 1)
    paginator = Paginator(object_list, 6) # 6 article per page
    try:
        page_obj = paginator.page(page_num)
    except PageNotAnInteger:
        # if page is not an integer, deliver the first page
        page_obj = paginator.page(1)
    except EmptyPage:
        # if the page is out of range, deliver the last page
        page_obj = paginator.page(paginator.num_pages)
    contex['page_obj']=page_obj
    labellist = label.objects.filter(parentcategory=5) # parentcategory 5 belongs to help
    contex['labellist']=labellist
    contex['labelvalue']=labelvalue

    return render(request, "mainapp/help.html", contex)

def userlogin(request):
    contex={'Alert':''}
    if request.method=='POST':
        if 'username' in request.POST and 'password' in request.POST:
            username = request.POST['username']
            password = request.POST['password']

            user = authenticate(username= username, password=password)
            if user is not None:
                login(request, user)
                return redirect("home")
            else:
                contex['Alert']="Login Credentials could not match/ wrong credentials"
        return render(request, "mainapp/login.html", contex)     
    return render(request, "mainapp/login.html", contex)

def userlogout(request):
    request.session.clear()
    logout(request)
    return redirect(home)

def createuser(request):
    pass

@login_required(login_url='/userlogin')
def addarticle(request):
    contex={}
    if request.method == 'POST':
        form = articleform(request.POST,request.FILES)
        if form.is_valid():
            form.author = request.user.id     
            lbl = label.objects.get(lid=request.POST['label'])
            if int(request.POST['category']) == int(lbl.parentcategory.cid):
                form.save()
                return redirect(help)
            else:
                contex['Alert']="Input category and label category dont match please create new or change accordingly"
    artform = articleform()
    contex['artform']=artform
    return render(request, "mainapp/addarticle.html", contex)

def about(request):
    contex={}
    project = article.objects.filter(category=7).order_by('-postdate')[0:6]
    contex['project'] = project
    return render(request, "mainapp/about.html", contex)

@login_required(login_url='/userlogin')
def deletearticle(request, num):
    instance = article.objects.get(bid=num)
    instance.delete()
    return redirect(help)

def viewarticle(request, num):
    contx={}
    instance = article.objects.get(bid=num)
    contx['article']=instance
    return render(request, "mainapp/viewarticle.html", contx)

@login_required(login_url='/userlogin')
def updatearticle(request, pk):
    contex={}
    blog_post = get_object_or_404(article, bid=pk)
    if request.method == 'POST':
        form = articleform(request.POST, request.FILES, instance=blog_post)
        if form.is_valid():
            lbl = label.objects.get(lid=request.POST['label'])
            if int(request.POST['category']) == int(lbl.parentcategory.cid):
                form.save()
                return redirect('viewarticle', num=pk)
            else:
                contex['Alert']="Input category and label category dont match please create new or change accordingly"
    
    form = articleform(instance=blog_post)
    contex['artform']=form
    return render(request, "mainapp/addarticle.html", contex)


def contact(request):
    contex={}
    return render(request, "mainapp/contact.html", contex)


def government(request):
    contex={}
    return render(request, "mainapp/government.html", contex)


def organisation(request):
    contex={}
    return render(request, "mainapp/organisation.html", contex)

def institute(request):
    contex={}
    return render(request, "mainapp/institute.html", contex)


def individual(request):
    contex={}
    return render(request, "mainapp/individual.html", contex)

def csr(request):
    contex={}
    return render(request, "mainapp/csr.html", contex)

def getinvolved(request):
    contex = {}
    return render(request, "mainapp/getinvolved.html", contex)

def focusArea(request):
    contex={}
    return render(request, "mainapp/focusArea.html", contex)

def testimonial(request):
    contex={}
    return render(request, "mainapp/testimonial.html", contex)

mainapp/templates/mainapp/addarticle.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>HYF|Add Article</title>

    <style>
        #id_title {
            width: 80%;
        }

        #id_snippet {
            width: 80%;
            height: 100px;
        }
    </style>
</head>

<body>

    {% if Alert %}
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <strong>Alert: </strong> {{Alert}}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% endif %}

    <!-- Image and text -->
    <nav class="navbar navbar-white bg-white">
        <a class="navbar-brand text-dark" href="{% url 'home' %}">
            <img src="https://s3.ap-south-1.amazonaws.com/assets.ynos.in/startup-logos/YNOS63244.jpg" width="40"
                height="40" class="d-inline-block align-top " alt="Logo">
            Himalayan Yeti Foundation
        </a>
    </nav>

    <form method="post" enctype="multipart/form-data" class="w-75 p-3 mx-auto">
        {% csrf_token %}
        {{ artform.media }}
        {{ artform.as_p }}
        <button type="submit" class="btn btn-primary ">Submit</button>
    </form>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</body>

</html>

mainapp/templates/mainapp/contact.html
<!DOCTYPE html>
{% load static %}

<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>HYF|Contact</title>

    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="{% static 'css/contact.css' %}">
    <link rel="icon" type="image/x-icon" href="{% static 'img\favicon.ico' %}">
</head>

<body>

    <!-- Navbar -->
    <nav class="navbar">
        <div class="logo">
            <img src="https://s3.ap-south-1.amazonaws.com/assets.ynos.in/startup-logos/YNOS63244.jpg" alt="logo">
        </div>

        <input type="checkbox" id="checkbox_toggle" />
        <label for="checkbox_toggle" class="hamburger">&#9776;</label>

        <div class="list">
            <!-- <input type="text" placeholder="Type to search"> -->
            <li><a href="{% url 'home' %}">Home</a></li>
            <li><a href="{% url 'about' %}">About</a></li>
            <li><a href="{% url 'focusArea' %}">Focus Areas</a></li>

            <li><a href="{% url 'getinvolved' %}">Get Involved</a></li>
            <li><a href="{% url 'help' %}">Help Centre</a></li>

        </div>
    </nav>

    <!-- contact section -->
    <div class="section contact">
        <div class="container">
            <div class="row">
                <div class="heading">
                    <h1>Contact Us</h1>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <form action="" class="form">
                        <input type="text" class="name" placeholder="Name">
                        <input type="email" class="email" placeholder="Email">
                        <input type="text" class="subject" placeholder="Subject">
                        <textarea name="" id="" cols="30" rows="10" class="message" placeholder="Message"></textarea>
                        <button>SUBMIT</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <!-- footer -->
    <section class="section footer">
        <div class="container">
            <div class="row">
                <div class="col-1">
                    <div class="widget">
                        <h2>Connect with us</h2>
                        <div class="social">
                            <div class="person">
                                <h4>Nagender Singh</h4><br>
                                <h5>Founder Director</h5>
                                <h5>Himalayan Yeti Foundation</h5>
                                <br>
                                <a href="#"><i class="material-icons call"></i>+2(305) 587-3407</a><br>
                                <a href="#"><i class="material-icons email"></i>himalayanyetifoundation@gmail.com</a>
                            </div>
                            <div class="person">
                                <h4>Vikram Kothari</h4><br>
                                <h5>Advisor Director</h5>
                                <h5>Himalayan Yeti Foundation</h5>
                                <br>
                                <a href="#"><i class="material-icons call"></i>+919650933677</a><br>
                                <a href="#"><i class="material-icons email"></i>hyfconsultant@gmail.com</a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-2">
                    <div class="widget footer-widget">
                        <h4 class="text-capitalize mb-4 text-white">Quick Links</h4>

                        <ul class="list-unstyled footer-menu lh-35">
                            <li><a href="{% url 'contact' %}">Contact Us</a></li>
                            <li><a href="{% url 'help' %}">Blogs</a></li>
                            <li><a href="index#latesthome">Events</a></li>
                            <li><a href="{% url 'testimonial' %}">Testimonial</a></li>
                            <li><a href="csr#logosection">Partners</a></li>
                            <li><a href="#">SDG</a></li>
                            {% if user.is_authenticated %}
                            <li><a href="{% url 'createuser' %}">Create User</a></li>
                            <li><a href="{% url 'userlogout' %}">Logout</a></li>
                            {% else %}
                            <li><a href="{% url 'userlogin' %}">Login</a></li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </div>
            <div class="row media">
                <ul>
                    <li><a href=""><img src="{% static 'img/facebook.svg' %}" alt=""></a></li>
                    <li><a href=""><img src="{% static 'img/instagram.svg' %}" alt=""></a></li>
                    <li><a href=""><img src="{% static 'img/twitter.svg' %}" alt=""></a></li>
                </ul>
            </div>
        </div>
    </section>
</body>

</html>

mainapp/templates/mainapp/donation.html
<!doctype html>
{% load static %}

<!-- {% load static %} -->
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous"> -->

    <title>Donation Page</title>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/donation.css' %}">
    <link rel="icon" type="image/x-icon" href="{% static 'img\favicon.ico' %}">
</head>

<body>

    <!-- Navbar -->
    <nav class="navbar">
        <div class="logo">
            <img src="https://s3.ap-south-1.amazonaws.com/assets.ynos.in/startup-logos/YNOS63244.jpg" alt="logo">
        </div>

        <input type="checkbox" id="checkbox_toggle" />
        <label for="checkbox_toggle" class="hamburger"><span class="material-icons">menu</span></label>

        <div class="list">
            <!-- <input type="text" placeholder="Type to search"> -->
            <li><a href="{% url 'home' %}">Home</a></li>
            <li><a href="{% url 'about' %}">About</a></li>
            <li><a href="{% url 'focusArea' %}">Focus Areas</a></li>
            <li><a href="{% url 'getinvolved' %}">Get Involved</a></li>
            <li><a href="{% url 'help' %}">Blogs & article</a></li>
        </div>
    </nav>

    <div class="section donate">
        <div class="container">
            <div class="heading">
                <h4>Our journey is toward better Himalayas.</h4>
            </div>
            <div class="row">
                <div class="static">
                    <div class="card">
                        <div class="heading">
                            Bank Transfer
                        </div>
                        <div class="details">
                            <p><b>Account Name : </b> Lorem ipsum dolor</p>
                            <p><b>Bank Name : </b> Lorem ipsum dolor</p>
                            <p><b>Account Number : </b><i class="copy">Lorem ipsum dolor</i></p>
                            <p><b>IFSC code : </b><i class="copy">Lorem ipsum dolor</i></p>
                            <p><b>Account Type : </b> Lorem ipsum dolor</p>
                        </div>
                    </div>
                </div>

                <div class="dynamic">
                    <div class="card">
                        <div class="heading">
                            Onilne Payment
                        </div>
                        <form class="form" action="" method="post">
                            <!-- {% csrf_token %} -->
                    
                            <div class="name">
                                <!-- <label for="inputname">Full Name : </label> -->
                                <input type="text" name="name" class="form-control" id="inputname" placeholder="Please Enter Your Name" >
                            </div>
                    
                            <div class="email">
                                <!-- <label for="inputEmail">Email address</label> -->
                                <input type="email" name="email" class="inemail" id="inputEmail" aria-describedby="emailHelp"
                                    placeholder="Please Enter Your Email Address">
                                <!-- <small id="emailHelp" class="small">We'll never share your email with anyone else.</small> -->
                            </div>
                    
                            <div class="phone">
                                <!-- <label for="inputphoneno">Phone Number</label> -->
                                <input type="tel" name="phoneno" class="form-control" id="inputphoneno" placeholder="Phone no.">
                            </div>
                    
                            <div class="amount">
                                <!-- <label for="inputamount">Amount (&#8377;):</label><br> -->
                                <input type="number" name="amount" class="form-control" min="0" id="inputamount" placeholder="&#8377; 0"
                                    aria-describedby="amounthelp">
                                <!-- <small id="amounthelp" class="form-text text-muted"></small> -->
                            </div>
                    
                            <div class="Comment">
                                <!-- <label for="inputcomments">Comments</label> -->
                                <textarea class="inputcomment" name="comment" id="inputcomments" rows="3" placeholder="Add comment"></textarea>
                            </div>
                    
                            <a href="#" target="_blank" class="btn btn-main animated rounded">Donate Now</a>
                    
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <!-- footer -->
    <section class="section footer">
        <div class="container">
            <div class="row">
                <div class="col-1">
                    <div class="widget">
                        <h2>Connect with us</h2>
                        <div class="social">
                            <div class="person">
                                <h4>Nagender Singh</h4><br>
                                <h5>Founder Director</h5>
                                <h5>Himalayan Yeti Foundation</h5>
                                <br>
                                <!-- <a href="#"><i class="material-icons call"></i>+2(305) 587-3407</a><br> -->
                                <a href="#"><i class="material-icons email"></i>himalayanyetifoundation@gmail.com</a>
                            </div>
                            <div class="person">
                                <h4>Vikram Kothari</h4><br>
                                <h5>Advisor Director</h5>
                                <h5>Himalayan Yeti Foundation</h5>
                                <br>
                                <!-- <a href="#"><i class="material-icons call"></i>+919650933677</a><br> -->
                                <a href="#"><i class="material-icons email"></i>hyfconsultant@gmail.com</a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-2">
                    <div class="widget footer-widget">
                        <h4 class="text-capitalize mb-4 text-white">Quick Links</h4>

                        <ul class="list-unstyled footer-menu lh-35">
                            <li><a href="{% url 'contact' %}">Contact Us</a></li>
                            <li><a href="{% url 'help' %}">Blogs</a></li>
                            <li><a href="index#latesthome">Events</a></li>
                            <li><a href="{% url 'testimonial' %}">Testimonial</a></li>
                            <li><a href="csr#logosection">Partners</a></li>
                            <li><a href="#">SDG</a></li>
                            {% if user.is_authenticated %}
                            <li><a href="{% url 'createuser' %}">Create User</a></li>
                            <li><a href="{% url 'userlogout' %}">Logout</a></li>
                            {% else %}
                            <li><a href="{% url 'userlogin' %}">Login</a></li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </div>
            <div class="row media">
                <ul>
                    <li><a href=""><img src="{% static 'img/facebook.svg' %}" alt=""></a></li>
                    <li><a href=""><img src="{% static 'img/instagram.svg' %}" alt=""></a></li>
                    <li><a href=""><img src="{% static 'img/twitter.svg' %}" alt=""></a></li>
                </ul>
            </div>
        </div>
    </section>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</body>

</html>

mainapp/templates/mainapp/government.html
<!DOCTYPE html>
{% load static %}

<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>HYF|Government</title>

    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="{% static 'css/government.css' %}">
    <link rel="icon" type="image/x-icon" href="{% static 'img\favicon.ico' %}">
</head>

<body>
    <!-- Navbar -->
    <nav class="navbar">
        <div class="logo">
            <img src="https://s3.ap-south-1.amazonaws.com/assets.ynos.in/startup-logos/YNOS63244.jpg" alt="logo">
        </div>

        <input type="checkbox" id="checkbox_toggle" />
        <label for="checkbox_toggle" class="hamburger">&#9776;</label>

        <div class="list">
            <!-- <input type="text" placeholder="Type to search"> -->
            <li><a href="{% url 'home' %}">Home</a></li>
            <li><a href="{% url 'about' %}">About</a></li>
            <li><a href="{% url 'focusArea' %}">Focus Areas</a></li>

            <li><a href="{% url 'getinvolved' %}">Get Involved</a></li>
            <li><a href="{% url 'help' %}">Blogs & article</a></li>
        </div>
    </nav>

    <!--  -->
    <h1>governemnt Section</h1>
    <!-- footer -->
    <section class="section footer">
        <div class="container">
            <div class="row">
                <div class="col-1">
                    <div class="widget">
                        <h2>Connect with us</h2>
                        <div class="social">
                            <div class="person">
                                <h4>Nagender Singh</h4><br>
                                <h5>Founder Director</h5>
                                <h5>Himalayan Yeti Foundation</h5>
                                <br>
                                <a href="#"><i class="material-icons call"></i>+2(305) 587-3407</a><br>
                                <a href="#"><i class="material-icons email"></i>himalayanyetifoundation@gmail.com</a>
                            </div>
                            <div class="person">
                                <h4>Vikram Kothari</h4><br>
                                <h5>Advisor Director</h5>
                                <h5>Himalayan Yeti Foundation</h5>
                                <br>
                                <a href="#"><i class="material-icons call"></i>+919650933677</a><br>
                                <a href="#"><i class="material-icons email"></i>hyfconsultant@gmail.com</a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-2">
                    <div class="widget footer-widget">
                        <h4 class="text-capitalize mb-4 text-white">Quick Links</h4>

                        <ul class="list-unstyled footer-menu lh-35">
                            <li><a href="{% url 'contact' %}">Contact Us</a></li>
                            <li><a href="{% url 'help' %}">Blogs</a></li>
                            <li><a href="index#latesthome">Events</a></li>
                            <li><a href="{% url 'testimonial' %}">Testimonial</a></li>
                            <li><a href="csr#logosection">Partners</a></li>
                            <li><a href="#">SDG</a></li>
                            {% if user.is_authenticated %}
                            <li><a href="{% url 'createuser' %}">Create User</a></li>
                            <li><a href="{% url 'userlogout' %}">Logout</a></li>
                            {% else %}
                            <li><a href="{% url 'userlogin' %}">Login</a></li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </div>
            <div class="row media">
                <ul>
                    <li><a href=""><img src="{% static 'img/facebook.svg' %}" alt=""></a></li>
                    <li><a href=""><img src="{% static 'img/instagram.svg' %}" alt=""></a></li>
                    <li><a href=""><img src="{% static 'img/twitter.svg' %}" alt=""></a></li>
                </ul>
            </div>
        </div>
    </section>
</body>

</html>